// Shopify API response schemas for pel-shopify-views
// Generated by src/introspect.js
// API Version: 2024-01
//
// To regenerate with live API data:
//   SHOPIFY_STORE_URL=xxx SHOPIFY_ACCESS_TOKEN=xxx node src/introspect.js
//
// Query Mappings:
// - Product: products / product(id: ID!) - scope: read_products
// - ProductVariant: productVariants / productVariant(id: ID!) - scope: read_products
// - Collection: collections / collection(id: ID!) - scope: read_products
// - InventoryItem: inventoryItems / inventoryItem(id: ID!) - scope: read_inventory, read_products
// - InventoryLevel: inventoryLevels (via inventoryItem) / inventoryLevel(id: ID!) - scope: read_inventory
// - Location: locations / location(id: ID) - scope: read_locations
// - Metafield: metafields (via parent object) / metafield(id: ID!) - scope: varies by owner type

module.exports = {
  "apiVersion": "2024-01",
  "types": {
    "Product": {
      "name": "Product",
      "kind": "OBJECT",
      "description": "A product represents an individual item for sale in a Shopify store.",
      "fields": {
        "id": { "type": "ID!", "baseType": "ID", "required": true, "list": false, "description": "A globally-unique ID." },
        "handle": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "A unique human-friendly string of the product's title." },
        "title": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The title of the product." },
        "descriptionHtml": { "type": "HTML!", "baseType": "HTML", "required": true, "list": false, "description": "The description of the product, complete with HTML formatting." },
        "vendor": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The name of the product's vendor." },
        "productType": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The product type specified by the merchant." },
        "tags": { "type": "[String!]!", "baseType": "String", "required": true, "list": true, "description": "A comma separated list of tags that have been added to the product." },
        "status": { "type": "ProductStatus!", "baseType": "ProductStatus", "required": true, "list": false, "description": "The status of the product." },
        "category": { "type": "TaxonomyCategory", "baseType": "TaxonomyCategory", "required": false, "list": false, "description": "The product category specified by the merchant." },
        "seo": { "type": "SEO!", "baseType": "SEO", "required": true, "list": false, "description": "SEO information for the product." },
        "options": { "type": "[ProductOption!]!", "baseType": "ProductOption", "required": true, "list": true, "description": "A list of product options." },
        "variants": { "type": "ProductVariantConnection!", "baseType": "ProductVariantConnection", "required": true, "list": false, "description": "A list of the product's variants." },
        "media": { "type": "MediaConnection!", "baseType": "MediaConnection", "required": true, "list": false, "description": "The media associated with the product." },
        "collections": { "type": "CollectionConnection!", "baseType": "CollectionConnection", "required": true, "list": false, "description": "A list of the collections that include the product." },
        "metafields": { "type": "MetafieldConnection!", "baseType": "MetafieldConnection", "required": true, "list": false, "description": "A paginated list of metafields associated with the resource." },
        "priceRangeV2": { "type": "ProductPriceRangeV2!", "baseType": "ProductPriceRangeV2", "required": true, "list": false, "description": "The price range of the product." },
        "createdAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the product was created." },
        "updatedAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the product was last updated." },
        "publishedAt": { "type": "DateTime", "baseType": "DateTime", "required": false, "list": false, "description": "The date and time when the product was published to the Online Store channel." }
      }
    },
    "ProductVariant": {
      "name": "ProductVariant",
      "kind": "OBJECT",
      "description": "A product variant represents a different version of a product.",
      "fields": {
        "id": { "type": "ID!", "baseType": "ID", "required": true, "list": false, "description": "A globally-unique ID." },
        "sku": { "type": "String", "baseType": "String", "required": false, "list": false, "description": "The SKU for the variant." },
        "title": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The title of the product variant." },
        "price": { "type": "Money!", "baseType": "Money", "required": true, "list": false, "description": "The price of the product variant in the default shop currency." },
        "compareAtPrice": { "type": "Money", "baseType": "Money", "required": false, "list": false, "description": "The compare-at price of the variant in the default shop currency." },
        "barcode": { "type": "String", "baseType": "String", "required": false, "list": false, "description": "The barcode (for example, ISBN, UPC, or GTIN) associated with the variant." },
        "selectedOptions": { "type": "[SelectedOption!]!", "baseType": "SelectedOption", "required": true, "list": true, "description": "The product variant's selected options." },
        "inventoryQuantity": { "type": "Int", "baseType": "Int", "required": false, "list": false, "description": "The total sellable quantity of the variant." },
        "inventoryPolicy": { "type": "ProductVariantInventoryPolicy!", "baseType": "ProductVariantInventoryPolicy", "required": true, "list": false, "description": "Whether customers are allowed to place an order for the product variant when it's out of stock." },
        "inventoryItem": { "type": "InventoryItem!", "baseType": "InventoryItem", "required": true, "list": false, "description": "The inventory item associated with the variant." },
        "image": { "type": "Image", "baseType": "Image", "required": false, "list": false, "description": "The featured image for the variant." },
        "taxable": { "type": "Boolean!", "baseType": "Boolean", "required": true, "list": false, "description": "Whether a tax is charged when the product variant is sold." },
        "metafields": { "type": "MetafieldConnection!", "baseType": "MetafieldConnection", "required": true, "list": false, "description": "A paginated list of metafields associated with the resource." }
      }
    },
    "Collection": {
      "name": "Collection",
      "kind": "OBJECT",
      "description": "A collection represents a group of products.",
      "fields": {
        "id": { "type": "ID!", "baseType": "ID", "required": true, "list": false, "description": "A globally-unique ID." },
        "handle": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "A unique human-friendly string of the collection's title." },
        "title": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The title of the collection." },
        "descriptionHtml": { "type": "HTML!", "baseType": "HTML", "required": true, "list": false, "description": "The description of the collection, complete with HTML formatting." },
        "image": { "type": "Image", "baseType": "Image", "required": false, "list": false, "description": "The image associated with the collection." },
        "seo": { "type": "SEO!", "baseType": "SEO", "required": true, "list": false, "description": "SEO information for the collection." },
        "sortOrder": { "type": "CollectionSortOrder!", "baseType": "CollectionSortOrder", "required": true, "list": false, "description": "The order in which the collection's products are sorted." },
        "ruleSet": { "type": "CollectionRuleSet", "baseType": "CollectionRuleSet", "required": false, "list": false, "description": "The rules used to assign products to the collection (for smart collections)." },
        "products": { "type": "ProductConnection!", "baseType": "ProductConnection", "required": true, "list": false, "description": "The products in the collection." },
        "productsCount": { "type": "Count", "baseType": "Count", "required": false, "list": false, "description": "The number of products in the collection." },
        "metafields": { "type": "MetafieldConnection!", "baseType": "MetafieldConnection", "required": true, "list": false, "description": "A paginated list of metafields associated with the resource." },
        "updatedAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the collection was last modified." }
      }
    },
    "InventoryItem": {
      "name": "InventoryItem",
      "kind": "OBJECT",
      "description": "An inventory item represents a physical good.",
      "fields": {
        "id": { "type": "ID!", "baseType": "ID", "required": true, "list": false, "description": "A globally-unique ID." },
        "sku": { "type": "String", "baseType": "String", "required": false, "list": false, "description": "The SKU of the inventory item." },
        "tracked": { "type": "Boolean!", "baseType": "Boolean", "required": true, "list": false, "description": "Whether the inventory item is tracked." },
        "unitCost": { "type": "MoneyV2", "baseType": "MoneyV2", "required": false, "list": false, "description": "Unit cost associated with the inventory item." },
        "countryCodeOfOrigin": { "type": "CountryCode", "baseType": "CountryCode", "required": false, "list": false, "description": "The ISO 3166-1 alpha-2 country code of where the item originated from." },
        "provinceCodeOfOrigin": { "type": "String", "baseType": "String", "required": false, "list": false, "description": "The province code of where the item originated from." },
        "harmonizedSystemCode": { "type": "String", "baseType": "String", "required": false, "list": false, "description": "The harmonized system code of the inventory item." },
        "requiresShipping": { "type": "Boolean!", "baseType": "Boolean", "required": true, "list": false, "description": "Whether the inventory item requires shipping." },
        "inventoryLevels": { "type": "InventoryLevelConnection!", "baseType": "InventoryLevelConnection", "required": true, "list": false, "description": "The inventory item's quantities at the location." },
        "measurement": { "type": "InventoryItemMeasurement!", "baseType": "InventoryItemMeasurement", "required": true, "list": false, "description": "The weight and dimensions of the inventory item." },
        "variant": { "type": "ProductVariant", "baseType": "ProductVariant", "required": false, "list": false, "description": "The variant that owns this inventory item." },
        "createdAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the inventory item was created." },
        "updatedAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the inventory item was last updated." }
      }
    },
    "InventoryLevel": {
      "name": "InventoryLevel",
      "kind": "OBJECT",
      "description": "An inventory level represents the available quantity of an inventory item at a location.",
      "fields": {
        "id": { "type": "ID!", "baseType": "ID", "required": true, "list": false, "description": "A globally-unique ID." },
        "available": { "type": "Int", "baseType": "Int", "required": false, "list": false, "description": "The available quantity at the location." },
        "item": { "type": "InventoryItem!", "baseType": "InventoryItem", "required": true, "list": false, "description": "The inventory item." },
        "location": { "type": "Location!", "baseType": "Location", "required": true, "list": false, "description": "The location." },
        "quantities": { "type": "[InventoryQuantity!]!", "baseType": "InventoryQuantity", "required": true, "list": true, "description": "The quantities for the inventory level." },
        "updatedAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the inventory level was last updated." }
      }
    },
    "Location": {
      "name": "Location",
      "kind": "OBJECT",
      "description": "A location represents a geographical location where your stores, pop-up stores, headquarters, and warehouses exist.",
      "fields": {
        "id": { "type": "ID!", "baseType": "ID", "required": true, "list": false, "description": "A globally-unique ID." },
        "name": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The name of the location." },
        "address": { "type": "LocationAddress!", "baseType": "LocationAddress", "required": true, "list": false, "description": "The address of the location." },
        "isActive": { "type": "Boolean!", "baseType": "Boolean", "required": true, "list": false, "description": "Whether the location is active." },
        "fulfillsOnlineOrders": { "type": "Boolean!", "baseType": "Boolean", "required": true, "list": false, "description": "Whether the location can fulfill online orders." },
        "shipsInventory": { "type": "Boolean!", "baseType": "Boolean", "required": true, "list": false, "description": "Whether the location is used for inventory shipping." },
        "inventoryLevels": { "type": "InventoryLevelConnection!", "baseType": "InventoryLevelConnection", "required": true, "list": false, "description": "The inventory levels at the location." },
        "createdAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the location was created." },
        "updatedAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the location was last updated." }
      }
    },
    "Metafield": {
      "name": "Metafield",
      "kind": "OBJECT",
      "description": "Metafields enable you to attach additional information to a Shopify resource.",
      "fields": {
        "id": { "type": "ID!", "baseType": "ID", "required": true, "list": false, "description": "A globally-unique ID." },
        "namespace": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The namespace for the metafield." },
        "key": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The key name for the metafield." },
        "value": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The data stored in the metafield." },
        "type": { "type": "String!", "baseType": "String", "required": true, "list": false, "description": "The type of data that the metafield stores." },
        "description": { "type": "String", "baseType": "String", "required": false, "list": false, "description": "A description of the metafield." },
        "ownerType": { "type": "MetafieldOwnerType!", "baseType": "MetafieldOwnerType", "required": true, "list": false, "description": "The type of resource that the metafield is attached to." },
        "createdAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the metafield was created." },
        "updatedAt": { "type": "DateTime!", "baseType": "DateTime", "required": true, "list": false, "description": "The date and time when the metafield was last updated." }
      }
    }
  },
  "queryMappings": {
    "Product": {
      "listQuery": "products",
      "singleQuery": "product(id: ID!)",
      "scope": "read_products"
    },
    "ProductVariant": {
      "listQuery": "productVariants",
      "singleQuery": "productVariant(id: ID!)",
      "scope": "read_products"
    },
    "Collection": {
      "listQuery": "collections",
      "singleQuery": "collection(id: ID!)",
      "scope": "read_products"
    },
    "InventoryItem": {
      "listQuery": "inventoryItems",
      "singleQuery": "inventoryItem(id: ID!)",
      "scope": "read_inventory, read_products"
    },
    "InventoryLevel": {
      "listQuery": "inventoryLevels (via inventoryItem)",
      "singleQuery": "inventoryLevel(id: ID!)",
      "scope": "read_inventory"
    },
    "Location": {
      "listQuery": "locations",
      "singleQuery": "location(id: ID)",
      "scope": "read_locations"
    },
    "Metafield": {
      "listQuery": "metafields (via parent object)",
      "singleQuery": "metafield(id: ID!)",
      "scope": "varies by owner type"
    }
  },
  "enums": {
    "ProductStatus": {
      "values": ["ACTIVE", "ARCHIVED", "DRAFT"],
      "description": "The status of a product."
    },
    "ProductVariantInventoryPolicy": {
      "values": ["DENY", "CONTINUE"],
      "description": "The inventory policy for a product variant."
    },
    "CollectionSortOrder": {
      "values": ["ALPHA_ASC", "ALPHA_DESC", "BEST_SELLING", "CREATED", "CREATED_DESC", "MANUAL", "PRICE_ASC", "PRICE_DESC"],
      "description": "The order of products in a collection."
    },
    "MetafieldOwnerType": {
      "values": ["ARTICLE", "BLOG", "COLLECTION", "CUSTOMER", "DRAFTORDER", "LOCATION", "ORDER", "PAGE", "PRODUCT", "PRODUCTVARIANT", "SHOP"],
      "description": "The type of resource that owns a metafield."
    }
  },
  "supportingTypes": {
    "SEO": {
      "fields": {
        "title": { "type": "String", "description": "The SEO title." },
        "description": { "type": "String", "description": "The SEO description." }
      }
    },
    "Image": {
      "fields": {
        "id": { "type": "ID!", "description": "A globally-unique ID." },
        "url": { "type": "URL!", "description": "The location of the image." },
        "altText": { "type": "String", "description": "A word or phrase to share the nature or contents of an image." },
        "width": { "type": "Int", "description": "The original width of the image in pixels." },
        "height": { "type": "Int", "description": "The original height of the image in pixels." }
      }
    },
    "LocationAddress": {
      "fields": {
        "address1": { "type": "String", "description": "The first line of the address." },
        "address2": { "type": "String", "description": "The second line of the address." },
        "city": { "type": "String", "description": "The city." },
        "province": { "type": "String", "description": "The province or state." },
        "provinceCode": { "type": "String", "description": "The two-letter province or state code." },
        "country": { "type": "String", "description": "The country." },
        "countryCode": { "type": "String", "description": "The two-letter country code." },
        "zip": { "type": "String", "description": "The ZIP or postal code." },
        "phone": { "type": "String", "description": "The phone number." }
      }
    },
    "SelectedOption": {
      "fields": {
        "name": { "type": "String!", "description": "The option name." },
        "value": { "type": "String!", "description": "The option value." }
      }
    },
    "MoneyV2": {
      "fields": {
        "amount": { "type": "Decimal!", "description": "The decimal money amount." },
        "currencyCode": { "type": "CurrencyCode!", "description": "The three-letter currency code." }
      }
    },
    "CollectionRuleSet": {
      "fields": {
        "appliedDisjunctively": { "type": "Boolean!", "description": "Whether products must match any or all of the rules." },
        "rules": { "type": "[CollectionRule!]!", "description": "The rules that define which products are included in the collection." }
      }
    },
    "CollectionRule": {
      "fields": {
        "column": { "type": "CollectionRuleColumn!", "description": "The attribute used for the rule condition." },
        "relation": { "type": "CollectionRuleRelation!", "description": "The type of operator used for the rule condition." },
        "condition": { "type": "String!", "description": "The value used for the rule condition." }
      }
    },
    "InventoryQuantity": {
      "fields": {
        "name": { "type": "String!", "description": "The name of the inventory quantity type (available, incoming, committed, etc.)." },
        "quantity": { "type": "Int!", "description": "The quantity." }
      }
    },
    "InventoryItemMeasurement": {
      "fields": {
        "weight": { "type": "Weight", "description": "The weight of the item." }
      }
    },
    "Weight": {
      "fields": {
        "unit": { "type": "WeightUnit!", "description": "The unit of measurement." },
        "value": { "type": "Float!", "description": "The weight value." }
      }
    }
  }
};
